---
HOSTS:
  el8:
    platform: el-8-x86_64
    box: generic/rocky8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: rocky-linux-cloud/rocky-linux-8
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  vagrant_cpus: 2
  type: aio
  multi_node: false
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
